@extends('frontend.layouts.app')

@section('content')

<!-- Hero Section Slider -->
<section id="home" class="relative w-full h-[60vh] md:h-[80vh] overflow-hidden">
    <!-- Slider Container -->
    <div id="slider-container" class="flex h-full transition-transform duration-700 ease-in-out">

        <!-- Slide 1: Promo Umum -->
        <div class="slide min-w-full h-full relative bg-cover bg-center" style="background-image: url('https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&auto=format&fit=crop');">
            <div class="absolute inset-0 bg-black bg-opacity-50 flex items-center">
                <div class="container mx-auto px-4 text-white animate-text-in">
                    <div class="max-w-2xl">
                        <h2 class="text-4xl md:text-6xl font-bold mb-4 leading-tight">Temukan Mobil Impian Anda</h2>
                        <p class="text-xl md:text-2xl mb-8 text-gray-200">Koleksi mobil bekas berkualitas dengan harga dan kondisi terbaik di Pekanbaru.</p>
                        <a href="#katalog" class="bg-purple-600 text-white px-8 py-4 rounded-full font-bold hover:bg-purple-700 transition transform hover:scale-105 inline-block">
                            <i class="fas fa-car mr-2"></i> Lihat Katalog
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <!-- Slide 2: Promo DP Ringan -->
        <div class="slide min-w-full h-full relative bg-cover bg-center" style="background-image: url('https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200&auto=format&fit=crop');">
            <div class="absolute inset-0 bg-black bg-opacity-50 flex items-center">
                <div class="container mx-auto px-4 text-white animate-text-in">
                    <div class="max-w-2xl">
                        <span class="bg-red-500 text-white px-4 py-1 rounded-full text-sm font-semibold mb-3 inline-block">PROMO SPESIAL</span>
                        <h2 class="text-4xl md:text-6xl font-bold mb-4 leading-tight">DP Ringan, Angsuran Terjangkau</h2>
                        <p class="text-xl md:text-2xl mb-8 text-gray-200">Miliki mobil idaman dengan skema kredit fleksibel. Proses cepat dan mudah dibantu sampai deal!</p>
                        <a href="#katalog" class="bg-white text-purple-700 px-8 py-4 rounded-full font-bold hover:bg-gray-200 transition transform hover:scale-105 inline-block">
                            <i class="fas fa-calculator mr-2"></i> Cek Simulasi Kredit
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <!-- Slide 3: Promo Tukar Tambah -->
        <div class="slide min-w-full h-full relative bg-cover bg-center" style="background-image: url('https://images.unsplash.com/photo-1616422285855-b9b2b5a5b5b5?w=1200&auto=format&fit=crop');">
            <div class="absolute inset-0 bg-black bg-opacity-50 flex items-center">
                <div class="container mx-auto px-4 text-white animate-text-in">
                     <div class="max-w-2xl">
                        <h2 class="text-4xl md:text-6xl font-bold mb-4 leading-tight">Tukar Tambah? Tentu Bisa!</h2>
                        <p class="text-xl md:text-2xl mb-8 text-gray-200">Dapatkan penawaran harga terbaik untuk mobil lama Anda. Tukar dengan unit yang lebih baru di showroom kami.</p>
                        <a href="https://wa.me/6281380846977" target="_blank" class="bg-green-500 text-white px-8 py-4 rounded-full font-bold hover:bg-green-600 transition transform hover:scale-105 inline-block">
                            <i class="fab fa-whatsapp mr-2"></i> Konsultasi Sekarang
                        </a>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Navigation Buttons -->
    <button id="prevBtn" class="absolute top-1/2 left-4 transform -translate-y-1/2 bg-white bg-opacity-50 hover:bg-opacity-100 text-gray-800 p-3 rounded-full transition">
        <i class="fas fa-chevron-left"></i>
    </button>
    <button id="nextBtn" class="absolute top-1/2 right-4 transform -translate-y-1/2 bg-white bg-opacity-50 hover:bg-opacity-100 text-gray-800 p-3 rounded-full transition">
        <i class="fas fa-chevron-right"></i>
    </button>

    <!-- Navigation Dots -->
    <div id="dots-container" class="absolute bottom-5 left-1/2 -translate-x-1/2 flex space-x-2">
        <!-- Dots will be generated by JS -->
    </div>
</section>
<!-- End of Hero Section Slider -->


    <!-- Keunggulan Layanan -->
    <section id="layanan" class="py-16 bg-white">
        <div class="container mx-auto px-4">
            <h3 class="text-3xl font-bold text-center mb-12 text-gray-800">Mengapa Memilih Kami?</h3>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
                <div class="text-center card-hover bg-gradient-to-br from-purple-50 to-white p-8 rounded-2xl shadow-lg">
                    <div class="bg-purple-100 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-4">
                        <i class="fas fa-check-circle text-3xl text-purple-600"></i>
                    </div>
                    <h4 class="text-xl font-bold mb-3 text-gray-800">Jaminan Kualitas</h4>
                    <p class="text-gray-600">Mobil sudah melewati inspeksi ketat untuk memastikan kondisi prima</p>
                </div>
                <div class="text-center card-hover bg-gradient-to-br from-green-50 to-white p-8 rounded-2xl shadow-lg">
                    <div class="bg-green-100 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-4">
                        <i class="fas fa-sync-alt text-3xl text-green-600"></i>
                    </div>
                    <h4 class="text-xl font-bold mb-3 text-gray-800">Terima Tukar Tambah</h4>
                    <p class="text-gray-600">Proses mudah dan penawaran terbaik untuk mobil lama Anda</p>
                </div>
                <div class="text-center card-hover bg-gradient-to-br from-blue-50 to-white p-8 rounded-2xl shadow-lg">
                    <div class="bg-blue-100 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-4">
                        <i class="fas fa-money-bill-wave text-3xl text-blue-600"></i>
                    </div>
                    <h4 class="text-xl font-bold mb-3 text-gray-800">Cash & Kredit</h4>
                    <p class="text-gray-600">Pilihan pembayaran fleksibel dengan DP rendah</p>
                </div>
            </div>
        </div>
    </section>

    <!-- Pencarian Cepat -->
    <section class="py-12 bg-gradient-to-r from-purple-100 to-blue-100">
        <div class="container mx-auto px-4">
            <h3 class="text-2xl font-bold text-center mb-8 text-gray-800">Pencarian Cepat</h3>
            <div class="bg-white rounded-2xl shadow-xl p-6 max-w-4xl mx-auto">
                <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
                    <select class="border-2 border-gray-200 rounded-lg px-4 py-3 focus:border-purple-500 focus:outline-none">
                        <option>Pilih Merek</option>
                        <option>Toyota</option>
                        <option>Daihatsu</option>
                        <option>Honda</option>
                        <option>Mitsubishi</option>
                        <option>Suzuki</option>
                    </select>
                    <select class="border-2 border-gray-200 rounded-lg px-4 py-3 focus:border-purple-500 focus:outline-none">
                        <option>Pilih Tipe</option>
                        <option>Avanza</option>
                        <option>Ayla</option>
                        <option>Brio</option>
                        <option>Xpander</option>
                        <option>Ertiga</option>
                    </select>
                    <select class="border-2 border-gray-200 rounded-lg px-4 py-3 focus:border-purple-500 focus:outline-none">
                        <option>Rentang Harga</option>
                        <option>&lt; 100 Juta</option>
                        <option>100 - 150 Juta</option>
                        <option>150 - 200 Juta</option>
                        <option>&gt; 200 Juta</option>
                    </select>
                    <button class="bg-purple-600 text-white rounded-lg px-6 py-3 font-bold hover:bg-purple-700 transition transform hover:scale-105">
                        <i class="fas fa-search mr-2"></i> Cari Mobil
                    </button>
                </div>
            </div>
        </div>
    </section>

    <!-- Katalog Mobil / Stok Terbaru -->
    <section id="katalog" class="py-16 bg-gray-50">
        <div class="container mx-auto px-4">
            <h3 class="text-3xl font-bold text-center mb-12 text-gray-800">Stok Mobil Terbaru</h3>

            <!-- Filter Options -->
            <div class="mb-8 bg-white rounded-xl p-4 shadow-md">
                <div class="flex flex-wrap gap-4 items-center">
                    <span class="font-semibold">Filter:</span>
                    <button class="px-4 py-2 bg-purple-100 text-purple-700 rounded-lg hover:bg-purple-200 transition">
                        <i class="fas fa-filter mr-1"></i> Semua
                    </button>
                    <button class="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition">
                        Manual
                    </button>
                    <button class="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition">
                        Otomatis
                    </button>
                    <div class="ml-auto flex items-center gap-2">
                        <span class="text-sm">Urutkan:</span>
                        <select class="border rounded-lg px-3 py-2 text-sm">
                            <option>Terbaru</option>
                            <option>Harga Terendah</option>
                            <option>Harga Tertinggi</option>
                        </select>
                    </div>
                </div>
            </div>

            <!-- Grid Mobil -->
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <!-- Mobil 1 -->
                <div class="bg-white rounded-2xl shadow-lg overflow-hidden card-hover">
                    <div class="relative">
                        <img src="https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=400" alt="Daihatsu Ayla" class="w-full h-48 object-cover">
                        <span class="absolute top-4 right-4 bg-red-500 text-white px-3 py-1 rounded-full text-sm font-bold">
                            HOT DEAL
                        </span>
                    </div>
                    <div class="p-6">
                        <h4 class="text-xl font-bold text-gray-800 mb-2">Daihatsu Ayla 1.0 X MT</h4>
                        <div class="flex items-center gap-2 text-sm text-gray-600 mb-4">
                            <span><i class="fas fa-calendar"></i> 2020</span>
                            <span><i class="fas fa-road"></i> 45.000 km</span>
                            <span><i class="fas fa-cog"></i> Manual</span>
                        </div>
                        <div class="border-t pt-4">
                            <p class="text-2xl font-bold text-purple-600">Rp 110.000.000</p>
                            <p class="text-sm text-green-600 font-semibold mt-1">
                                <i class="fas fa-tag"></i> DP Mulai 10 Juta
                            </p>
                        </div>
                        <button onclick="showDetail('Daihatsu Ayla 1.0 X MT 2020')" class="w-full mt-4 bg-purple-600 text-white py-3 rounded-lg font-bold hover:bg-purple-700 transition">
                            Lihat Detail
                        </button>
                    </div>
                </div>

                <!-- Mobil 2 -->
                <div class="bg-white rounded-2xl shadow-lg overflow-hidden card-hover">
                    <div class="relative">
                        <img src="https://images.unsplash.com/photo-1550355291-bbee04a92027?w=400" alt="Toyota Avanza" class="w-full h-48 object-cover">
                        <span class="absolute top-4 right-4 bg-green-500 text-white px-3 py-1 rounded-full text-sm font-bold">
                            BEST SELLER
                        </span>
                    </div>
                    <div class="p-6">
                        <h4 class="text-xl font-bold text-gray-800 mb-2">Toyota Avanza 1.3 G MT</h4>
                        <div class="flex items-center gap-2 text-sm text-gray-600 mb-4">
                            <span><i class="fas fa-calendar"></i> 2018</span>
                            <span><i class="fas fa-road"></i> 60.000 km</span>
                            <span><i class="fas fa-cog"></i> Manual</span>
                        </div>
                        <div class="border-t pt-4">
                            <p class="text-2xl font-bold text-purple-600">Rp 158.000.000</p>
                            <p class="text-sm text-green-600 font-semibold mt-1">
                                <i class="fas fa-tag"></i> DP Mulai 20 Juta
                            </p>
                        </div>
                        <button onclick="showDetail('Toyota Avanza 1.3 G MT 2018')" class="w-full mt-4 bg-purple-600 text-white py-3 rounded-lg font-bold hover:bg-purple-700 transition">
                            Lihat Detail
                        </button>
                    </div>
                </div>

                <!-- Mobil 3 -->
                <div class="bg-white rounded-2xl shadow-lg overflow-hidden card-hover">
                    <div class="relative">
                        <img src="https://images.unsplash.com/photo-1588636142475-a62d56692870?w=400" alt="Honda Brio" class="w-full h-48 object-cover">
                        <span class="absolute top-4 right-4 bg-blue-500 text-white px-3 py-1 rounded-full text-sm font-bold">
                            READY
                        </span>
                    </div>
                    <div class="p-6">
                        <h4 class="text-xl font-bold text-gray-800 mb-2">Honda Brio Satya E CVT</h4>
                        <div class="flex items-center gap-2 text-sm text-gray-600 mb-4">
                            <span><i class="fas fa-calendar"></i> 2019</span>
                            <span><i class="fas fa-road"></i> 35.000 km</span>
                            <span><i class="fas fa-cog"></i> Otomatis</span>
                        </div>
                        <div class="border-t pt-4">
                            <p class="text-2xl font-bold text-purple-600">Rp 145.000.000</p>
                            <p class="text-sm text-green-600 font-semibold mt-1">
                                <i class="fas fa-tag"></i> DP Mulai 15 Juta
                            </p>
                        </div>
                        <button onclick="showDetail('Honda Brio Satya E CVT 2019')" class="w-full mt-4 bg-purple-600 text-white py-3 rounded-lg font-bold hover:bg-purple-700 transition">
                            Lihat Detail
                        </button>
                    </div>
                </div>

                <!-- Mobil 4 -->
                <div class="bg-white rounded-2xl shadow-lg overflow-hidden card-hover">
                    <div class="relative">
                        <img src="https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=400" alt="Mitsubishi Xpander" class="w-full h-48 object-cover">
                        <span class="absolute top-4 right-4 bg-orange-500 text-white px-3 py-1 rounded-full text-sm font-bold">
                            PROMO
                        </span>
                    </div>
                    <div class="p-6">
                        <h4 class="text-xl font-bold text-gray-800 mb-2">Mitsubishi Xpander GLS MT</h4>
                        <div class="flex items-center gap-2 text-sm text-gray-600 mb-4">
                            <span><i class="fas fa-calendar"></i> 2021</span>
                            <span><i class="fas fa-road"></i> 25.000 km</span>
                            <span><i class="fas fa-cog"></i> Manual</span>
                        </div>
                        <div class="border-t pt-4">
                            <p class="text-2xl font-bold text-purple-600">Rp 235.000.000</p>
                            <p class="text-sm text-green-600 font-semibold mt-1">
                                <i class="fas fa-tag"></i> DP Mulai 35 Juta
                            </p>
                        </div>
                        <button onclick="showDetail('Mitsubishi Xpander GLS MT 2021')" class="w-full mt-4 bg-purple-600 text-white py-3 rounded-lg font-bold hover:bg-purple-700 transition">
                            Lihat Detail
                        </button>
                    </div>
                </div>

                <!-- Mobil 5 -->
                <div class="bg-white rounded-2xl shadow-lg overflow-hidden card-hover">
                    <div class="relative">
                        <img src="https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=400" alt="Suzuki Ertiga" class="w-full h-48 object-cover">
                    </div>
                    <div class="p-6">
                        <h4 class="text-xl font-bold text-gray-800 mb-2">Suzuki Ertiga GL MT</h4>
                        <div class="flex items-center gap-2 text-sm text-gray-600 mb-4">
                            <span><i class="fas fa-calendar"></i> 2020</span>
                            <span><i class="fas fa-road"></i> 40.000 km</span>
                            <span><i class="fas fa-cog"></i> Manual</span>
                        </div>
                        <div class="border-t pt-4">
                            <p class="text-2xl font-bold text-purple-600">Rp 175.000.000</p>
                            <p class="text-sm text-green-600 font-semibold mt-1">
                                <i class="fas fa-tag"></i> DP Mulai 25 Juta
                            </p>
                        </div>
                        <button onclick="showDetail('Suzuki Ertiga GL MT 2020')" class="w-full mt-4 bg-purple-600 text-white py-3 rounded-lg font-bold hover:bg-purple-700 transition">
                            Lihat Detail
                        </button>
                    </div>
                </div>

                <!-- Mobil 6 -->
                <div class="bg-white rounded-2xl shadow-lg overflow-hidden card-hover">
                    <div class="relative">
                        <img src="https://images.unsplash.com/photo-1581540222194-0def2dda95b8?w=400" alt="Toyota Rush" class="w-full h-48 object-cover">
                        <span class="absolute top-4 right-4 bg-purple-500 text-white px-3 py-1 rounded-full text-sm font-bold">
                            LIMITED
                        </span>
                    </div>
                    <div class="p-6">
                        <h4 class="text-xl font-bold text-gray-800 mb-2">Toyota Rush TRD Sportivo AT</h4>
                        <div class="flex items-center gap-2 text-sm text-gray-600 mb-4">
                            <span><i class="fas fa-calendar"></i> 2021</span>
                            <span><i class="fas fa-road"></i> 30.000 km</span>
                            <span><i class="fas fa-cog"></i> Otomatis</span>
                        </div>
                        <div class="border-t pt-4">
                            <p class="text-2xl font-bold text-purple-600">Rp 265.000.000</p>
                            <p class="text-sm text-green-600 font-semibold mt-1">
                                <i class="fas fa-tag"></i> DP Mulai 40 Juta
                            </p>
                        </div>
                        <button onclick="showDetail('Toyota Rush TRD Sportivo AT 2021')" class="w-full mt-4 bg-purple-600 text-white py-3 rounded-lg font-bold hover:bg-purple-700 transition">
                            Lihat Detail
                        </button>
                    </div>
                </div>
            </div>

            <!-- Load More Button -->
            <div class="text-center mt-12">
                <button class="bg-gradient-to-r from-purple-600 to-blue-600 text-white px-8 py-4 rounded-full font-bold hover:from-purple-700 hover:to-blue-700 transition transform hover:scale-105">
                    <i class="fas fa-plus-circle mr-2"></i> Lihat Lebih Banyak
                </button>
            </div>
        </div>
    </section>

    <!-- Kontak & Lokasi -->
    <section id="kontak" class="py-16 bg-white">
        <div class="container mx-auto px-4">
            <h3 class="text-3xl font-bold text-center mb-12 text-gray-800">Lokasi & Kontak Kami</h3>
            <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
                <div>
                    <div class="bg-gradient-to-br from-purple-50 to-blue-50 rounded-2xl p-8 h-full">
                        <h4 class="text-2xl font-bold mb-6 text-gray-800">Showroom Manunggal Mobilindo 2</h4>

                        <div class="space-y-4 mb-6">
                            <div class="flex items-start">
                                <i class="fas fa-map-marker-alt text-purple-600 mt-1 mr-4 text-xl"></i>
                                <div>
                                    <p class="font-semibold">Alamat:</p>
                                    <p class="text-gray-700">Jl. Soekarno Hatta No. 88, Arengka, Pekanbaru, Riau 28293</p>
                                </div>
                            </div>

                            <div class="flex items-start">
                                <i class="fas fa-clock text-purple-600 mt-1 mr-4 text-xl"></i>
                                <div>
                                    <p class="font-semibold">Jam Operasional:</p>
                                    <p class="text-gray-700">Senin - Sabtu: 08:00 - 17:00</p>
                                    <p class="text-gray-700">Minggu: 09:00 - 15:00</p>
                                </div>
                            </div>

                            <div class="flex items-start">
                                <i class="fas fa-phone text-purple-600 mt-1 mr-4 text-xl"></i>
                                <div>
                                    <p class="font-semibold">Telepon:</p>
                                    <p class="text-gray-700">0813-8084-6977</p>
                                    <p class="text-gray-700">0761-123456</p>
                                </div>
                            </div>

                            <div class="flex items-start">
                                <i class="fas fa-envelope text-purple-600 mt-1 mr-4 text-xl"></i>
                                <div>
                                    <p class="font-semibold">Email:</p>
                                    <p class="text-gray-700">info@manunggalmobilindo.com</p>
                                </div>
                            </div>
                        </div>

                        <div class="flex flex-col sm:flex-row gap-3">
                            <a href="https://wa.me/6281380846977" target="_blank" class="bg-green-500 text-white px-6 py-3 rounded-lg font-bold hover:bg-green-600 transition text-center">
                                <i class="fab fa-whatsapp mr-2"></i> Chat WhatsApp
                            </a>
                            <a href="tel:081380846977" class="bg-blue-500 text-white px-6 py-3 rounded-lg font-bold hover:bg-blue-600 transition text-center">
                                <i class="fas fa-phone mr-2"></i> Telepon Sekarang
                            </a>
                        </div>
                    </div>
                </div>

                <div>
                    <div class="bg-gray-200 rounded-2xl overflow-hidden h-full min-h-[400px]">
                        <!-- Embedded Google Maps -->
                        <iframe
                            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3989.6583684773!2d101.45506541475336!3d0.5070693996084!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31d5aedefc5b6b51%3A0x5f5160f9c2c3b9f2!2sPekanbaru%2C%20Riau!5e0!3m2!1sen!2sid!4v1234567890"
                            width="100%"
                            height="100%"
                            style="border:0; min-height: 400px;"
                            allowfullscreen=""
                            loading="lazy">
                        </iframe>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Testimonial Section -->
    <section class="py-16 bg-gradient-to-r from-purple-100 to-blue-100">
        <div class="container mx-auto px-4">
            <h3 class="text-3xl font-bold text-center mb-12 text-gray-800">Apa Kata Pelanggan Kami</h3>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div class="bg-white rounded-xl p-6 shadow-lg">
                    <div class="flex mb-4">
                        <i class="fas fa-star text-yellow-400"></i>
                        <i class="fas fa-star text-yellow-400"></i>
                        <i class="fas fa-star text-yellow-400"></i>
                        <i class="fas fa-star text-yellow-400"></i>
                        <i class="fas fa-star text-yellow-400"></i>
                    </div>
                    <p class="text-gray-600 mb-4">"Pelayanan sangat memuaskan! Proses kredit cepat dan mudah. Mobilnya berkualitas dan sesuai dengan deskripsi."</p>
                    <div class="flex items-center">
                        <div class="w-10 h-10 bg-purple-200 rounded-full mr-3"></div>
                        <div>
                            <p class="font-semibold">Budi Santoso</p>
                            <p class="text-sm text-gray-500">Pembeli Avanza 2018</p>
                        </div>
                    </div>
                </div>

                <div class="bg-white rounded-xl p-6 shadow-lg">
                    <div class="flex mb-4">
                        <i class="fas fa-star text-yellow-400"></i>
                        <i class="fas fa-star text-yellow-400"></i>
                        <i class="fas fa-star text-yellow-400"></i>
                        <i class="fas fa-star text-yellow-400"></i>
                        <i class="fas fa-star text-yellow-400"></i>
                    </div>
                    <p class="text-gray-600 mb-4">"Showroom terpercaya! Saya puas dengan mobil yang saya beli. Team sales sangat membantu dalam proses pembelian."</p>
                    <div class="flex items-center">
                        <div class="w-10 h-10 bg-green-200 rounded-full mr-3"></div>
                        <div>
                            <p class="font-semibold">Siti Rahma</p>
                            <p class="text-sm text-gray-500">Pembeli Brio 2019</p>
                        </div>
                    </div>
                </div>

                <div class="bg-white rounded-xl p-6 shadow-lg">
                    <div class="flex mb-4">
                        <i class="fas fa-star text-yellow-400"></i>
                        <i class="fas fa-star text-yellow-400"></i>
                        <i class="fas fa-star text-yellow-400"></i>
                        <i class="fas fa-star text-yellow-400"></i>
                        <i class="fas fa-star text-yellow-400"></i>
                    </div>
                    <p class="text-gray-600 mb-4">"Proses tukar tambah sangat mudah dan penawaran harga yang fair. Recommended untuk yang cari mobil bekas berkualitas!"</p>
                    <div class="flex items-center">
                        <div class="w-10 h-10 bg-blue-200 rounded-full mr-3"></div>
                        <div>
                            <p class="font-semibold">Ahmad Fauzi</p>
                            <p class="text-sm text-gray-500">Pembeli Xpander 2021</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
